name: Publish Electron App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

      - name: Verify DMG (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          echo "🔍 Searching for DMG files..."
          find out/make -name "*.dmg"

          echo "✅ Verifying DMG..."
          for dmg in $(find out/make -name "*.dmg"); do
            echo "Verifying $dmg"
            hdiutil verify "$dmg"
          done
